name: Build in Linux

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Build
        run: |
          g++ -shared -Wl,-soname,FPD_Random -o FPD_Random.so -fPIC src/FPD_Random.cpp
      
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ github.workspace }}
